development:
  primary:
    adapter: postgresql
    database: TwistedFroest_development

production:
  primary:
    adapter: postgresql
    url: <%= Rails.application.credentials.dig(:random, :database_url) %>
